version: "2"

services: 
  jenkinsdata: 
    build: jenkins-data
  jenkinsmaster: 
    build: jenkins-master
    ports: 
      - "50000:50000"
    networks:
      - front-tier
    volumes_from: 
      - jenkinsdata
    depends_on:
      - jenkinsdata 
  jenkinstomcat: 
    build: jenkins-tomcat
    networks:
      - front-tier
  jenkinsnginx: 
    build: jenkins-nginx
    ports: 
      - "80:80"
    networks:
      - front-tier
    volumes_from:
      - jenkinsdata
    depends_on:
      - jenkinsmaster
      - jenkinstomcat
      - jenkinsdata
      
networks:
  front-tier:
    driver: bridge

volumes:
  jenkinsdata: