jenkinsdata:
 build: jenkins-data
jenkinstomcat:
 build: jenkins-tomcat
 ports:
  - "8080:8080"  
jenkinsmaster:
 build: jenkins-master
 volumes_from:
  - jenkinsdata
 ports:
  - "50000:50000"
 links:
  - jenkinstomcat:jenkins-tomcat
jenkinsnginx:
 build: jenkins-nginx
 ports:
  - "80:80"
 links:
  - jenkinsmaster:jenkins-master